// ============================================================
// PRODUTO.JS — Catálogo com categorias: Eventos e Artísticas
// ============================================================

const EVENTOS = [
  {
    id: 'meia-maratona',
    nome: 'Meia Maratona',
    icone: '',
    fotos: [
      {
        id: 'mm-001',
        categoria: 'evento',
        eventoId: 'meia-maratona',
        nome: 'Largada da Meia Maratona',
        preco: 25.00,
        preview: 'img/foto1.jpeg',
        arquivo: 'foto1.jpeg',
      },
      {
        id: 'mm-002',
        categoria: 'evento',
        eventoId: 'meia-maratona',
        nome: 'Corredor em Destaque',
        preco: 25.00,
        preview: 'img/foto2.jpeg',
        arquivo: 'foto2.jpeg',
      },
      {
        id: 'mm-003',
        categoria: 'evento',
        eventoId: 'meia-maratona',
        nome: 'Chegada na Linha de Chegada',
        preco: 22.00,
        preview: 'img/foto3.jpeg',
        arquivo: 'foto3.jpeg',
      },
    ],
  },
  {
    id: 'triatlon',
    nome: 'Triátlon',
    icone: '',
    fotos: [
      {
        id: 'tri-001',
        categoria: 'evento',
        eventoId: 'triatlon',
        nome: 'Saída da Água',
        preco: 28.00,
        preview: 'img/foto4.jpeg',
        arquivo: 'foto4.jpeg',
      },
      {
        id: 'tri-002',
        categoria: 'evento',
        eventoId: 'triatlon',
        nome: 'Percurso de Ciclismo',
        preco: 28.00,
        preview: 'img/foto5.jpeg',
        arquivo: 'foto5.jpeg',
      },
    ],
  },
];

const CATEGORIAS_ARTISTICAS = [
  {
    id: 'paisagens',
    nome: 'Paisagens',
    icone: '',
    fotos: [
      {
        id: 'pai-001',
        categoria: 'artistica',
        categoriaArtId: 'paisagens',
        nome: 'Lagoa dos Pescadores',
        preco: 45.00,
        preview: 'img/lagoa-dos-pescadores.jpg',
        arquivo: 'lagoa-dos-pescadores.jpg',
      },
      {
        id: 'pai-002',
        categoria: 'artistica',
        categoriaArtId: 'paisagens',
        nome: 'Baía de Guanabara I',
        preco: 55.00,
        preview: 'img/baia-de-guanabara-1.jpg',
        arquivo: 'baia-de-guanabara-1.jpg',
      },
      {
        id: 'pai-003',
        categoria: 'artistica',
        categoriaArtId: 'paisagens',
        nome: 'Baía de Guanabara II',
        preco: 60.00,
        preview: 'img/baia-de-guanabara-2.jpg',
        arquivo: 'baia-de-guanabara-2.jpg',
      },
      {
        id: 'pai-004',
        categoria: 'artistica',
        categoriaArtId: 'paisagens',
        nome: 'Silhueta na Praia',
        preco: 58.00,
        preview: 'img/silhueta-na-praia.jpg',
        arquivo: 'silhueta-na-praia.jpg',
      },
      {
        id: 'pai-005',
        categoria: 'artistica',
        categoriaArtId: 'paisagens',
        nome: 'Veleiro ao Pôr do Sol',
        preco: 65.00,
        preview: 'img/veleiro-ao-por-do-sol.jpg',
        arquivo: 'veleiro-ao-por-do-sol.jpg',
      },
      {
        id: 'pai-006',
        categoria: 'artistica',
        categoriaArtId: 'paisagens',
        nome: 'Praia da Lagoa',
        preco: 50.00,
        preview: 'img/praia-da-lagoa.jpg',
        arquivo: 'praia-da-lagoa.jpg',
      },
      {
        id: 'pai-007',
        categoria: 'artistica',
        categoriaArtId: 'paisagens',
        nome: 'Posto do Salva-vidas',
        preco: 60.00,
        preview: 'img/posto-do-salva-vidas.jpg',
        arquivo: 'posto-do-salva-vidas.jpg',
      },
      {
        id: 'pai-008',
        categoria: 'artistica',
        categoriaArtId: 'paisagens',
        nome: 'Barco no Entardecer',
        preco: 50.00,
        preview: 'img/barco-no-entardecer.jpg',
        arquivo: 'barco-no-entardecer.jpg',
      },
      {
        id: 'pai-009',
        categoria: 'artistica',
        categoriaArtId: 'paisagens',
        nome: 'Entardecer no Riacho',
        preco: 48.00,
        preview: 'img/entardecer-no-riacho.jpg',
        arquivo: 'entardecer-no-riacho.jpg',
      },
      {
        id: 'pai-010',
        categoria: 'artistica',
        categoriaArtId: 'paisagens',
        nome: 'SUP com Dog',
        preco: 70.00,
        preview: 'img/sup-com-dog.jpg',
        arquivo: 'sup-com-dog.jpg',
      },
    ],
  },
  {
    id: 'retratos',
    nome: 'Retratos',
    icone: '',
    fotos: [
      {
        id: 'ret-001',
        categoria: 'artistica',
        categoriaArtId: 'retratos',
        nome: 'Retrato na Cachoeira',
        preco: 35.00,
        preview: 'img/retrato-na-cachoeira.jpg',
        arquivo: 'retrato-na-cachoeira.jpg',
      },
      {
        id: 'ret-002',
        categoria: 'artistica',
        categoriaArtId: 'retratos',
        nome: 'Retrato na Floresta I',
        preco: 32.00,
        preview: 'img/retrato-na-floresta-1.jpg',
        arquivo: 'retrato-na-floresta-1.jpg',
      },
      {
        id: 'ret-003',
        categoria: 'artistica',
        categoriaArtId: 'retratos',
        nome: 'Retrato na Floresta II',
        preco: 30.00,
        preview: 'img/retrato-na-floresta-2.jpg',
        arquivo: 'retrato-na-floresta-2.jpg',
      },
      {
        id: 'ret-004',
        categoria: 'artistica',
        categoriaArtId: 'retratos',
        nome: 'Retrato na Floresta III',
        preco: 30.00,
        preview: 'img/retrato-na-floresta-3.jpg',
        arquivo: 'retrato-na-floresta-3.jpg',
      },
      {
        id: 'ret-005',
        categoria: 'artistica',
        categoriaArtId: 'retratos',
        nome: 'Retrato na Praia I',
        preco: 35.00,
        preview: 'img/retrato-na-praia-1.jpg',
        arquivo: 'retrato-na-praia-1.jpg',
      },
      {
        id: 'ret-006',
        categoria: 'artistica',
        categoriaArtId: 'retratos',
        nome: 'Retrato na Praia II',
        preco: 32.00,
        preview: 'img/retrato-na-praia-2.jpg',
        arquivo: 'retrato-na-praia-2.jpg',
      },
      { 
        id: 'ret-007',
        categoria: 'artistica',
        categoriaArtId: 'retratos',
        nome: 'Retrato na Praia III',
        preco: 30.00,
        preview: 'img/retrato-na-praia-3.jpg',
        arquivo: 'retrato-na-praia-3.jpg',
      },
    ],
  },
  {
    id: 'animais',
    nome: 'Animais',
    icone: '',
    fotos: [
      {
        id: 'ani-001',
        categoria: 'artistica',
        categoriaArtId: 'animais',
        nome: 'Sanhaçu-pardo',
        preco: 55.00,
        preview: 'img/sanhacu-pardo.jpg',
        arquivo: 'sanhacu-pardo.jpg',
      },
      {
        id: 'ani-002',
        categoria: 'artistica',
        categoriaArtId: 'animais',
        nome: 'Saíra-de-cabeça-azul',
        preco: 55.00,
        preview: 'img/saira-de-cabeca-azul.jpg',
        arquivo: 'saira-de-cabeca-azul.jpg',
      },
      {
        id: 'ani-003',
        categoria: 'artistica',
        categoriaArtId: 'animais',
        nome: 'Sabiá-laranjeira',
        preco: 50.00,
        preview: 'img/sabia-laranjeira.jpg',
        arquivo: 'sabia-laranjeira.jpg',
      },
      {
        id: 'ani-004',
        categoria: 'artistica',
        categoriaArtId: 'animais',
        nome: 'Tico-tico',
        preco: 50.00,
        preview: 'img/tico-tico.jpg',
        arquivo: 'tico-tico.jpg',
      },
      {
        id: 'ani-005',
        categoria: 'artistica',
        categoriaArtId: 'animais',
        nome: 'Jacupemba',
        preco: 50.00,
        preview: 'img/jacupemba.jpg',
        arquivo: 'jacupemba.jpg',
      },
      {
        id: 'ani-006',
        categoria: 'artistica',
        categoriaArtId: 'animais',
        nome: 'Saíra-de-cabeça-castanha',
        preco: 60.00,
        preview: 'img/saira-de-cabeca-castanha.jpg',
        arquivo: 'saira-de-cabeca-castanha.jpg',
      },
      {
        id: 'ani-007',
        categoria: 'artistica',
        categoriaArtId: 'animais',
        nome: 'Anu-branco',
        preco: 60.00,
        preview: 'img/anu-branco.jpg',
        arquivo: 'anu-branco.jpg',
      },
      {
        id: 'ani-008',
        categoria: 'artistica',
        categoriaArtId: 'animais',
        nome: 'Sabiá-do-campo',
        preco: 50.00,
        preview: 'img/sabia-do-campo.jpg',
        arquivo: 'sabia-do-campo.jpg',
      },
      {
        id: 'ani-009',
        categoria: 'artistica',
        categoriaArtId: 'animais',
        nome: 'Pica-pau-dourado',
        preco: 65.00,
        preview: 'img/pica-pau-dourado.jpg',
        arquivo: 'pica-pau-dourado.jpg',
      },
    ],
  },
  {
    id: 'luar',
    nome: 'Luar',
    icone: '',
    fotos: [
      {
        id: 'lua-001',
        categoria: 'artistica',
        categoriaArtId: 'luar',
        nome: 'Lua Cheia',
        preco: 1.00,
        preview: 'img/lua-cheia.jpg',
        arquivo: 'lua-cheia.jpg',
      },
      {
        id: 'lua-002',
        categoria: 'artistica',
        categoriaArtId: 'luar',
        nome: 'Lua Minguante',
        preco: 85.00,
        preview: 'img/lua-minguante.jpg',
        arquivo: 'lua-minguante.jpg',
      },
    ],
  },
  {
    id: 'natureza',
    nome: 'Natureza',
    icone: '',
    fotos: [
      {
        id: 'nat-001',
        categoria: 'artistica',
        categoriaArtId: 'natureza',
        nome: 'Cachoeira na Mata',
        preco: 65.00,
        preview: 'img/cachoeira-na-mata.jpg',
        arquivo: 'cachoeira-na-mata.jpg',
      },
      {
        id: 'nat-002',
        categoria: 'artistica',
        categoriaArtId: 'natureza',
        nome: 'Canyon Itaimbezinho',
        preco: 80.00,
        preview: 'img/canyon-itaimbezinho.jpg',
        arquivo: 'canyon-itaimbezinho.jpg',
      },
      {
        id: 'nat-003',
        categoria: 'artistica',
        categoriaArtId: 'natureza',
        nome: 'Floresta com Nuvens',
        preco: 60.00,
        preview: 'img/floresta-com-nuvens.jpg',
        arquivo: 'floresta-com-nuvens.jpg',
      },
    ],
  },
  {
    id: 'serra',
    nome: 'Serra Gaúcha',
    icone: '',
    fotos: [
      {
        id: 'ser-001',
        categoria: 'artistica',
        categoriaArtId: 'serra',
        nome: 'Aparados da Serra I',
        preco: 60.00,
        preview: 'img/aparados-da-serra-1.jpg',
        arquivo: 'aparados-da-serra-1.jpg',
      },
      {
        id: 'ser-002',
        categoria: 'artistica',
        categoriaArtId: 'serra',
        nome: 'Aparados da Serra II',
        preco: 60.00,
        preview: 'img/aparados-da-serra-2.jpg',
        arquivo: 'aparados-da-serra-2.jpg',
      },
      {
        id: 'ser-003',
        categoria: 'artistica',
        categoriaArtId: 'serra',
        nome: 'Casinha Azul',
        preco: 65.00,
        preview: 'img/casinha-azul.jpg',
        arquivo: 'casinha-azul.jpg',
      },
      {
        id: 'ser-004',
        categoria: 'artistica',
        categoriaArtId: 'serra',
        nome: 'Casinha nas Araucárias',
        preco: 70.00,
        preview: 'img/casinha-nas-araucarias.jpg',
        arquivo: 'casinha-nas-araucarias.jpg',
      },
      {
        id: 'ser-005',
        categoria: 'artistica',
        categoriaArtId: 'serra',
        nome: 'Estrada no Planalto',
        preco: 65.00,
        preview: 'img/estrada-no-planalto.jpg',
        arquivo: 'estrada-no-planalto.jpg',
      },
      {
        id: 'ser-006',
        categoria: 'artistica',
        categoriaArtId: 'serra',
        nome: 'Corte da Rocha',
        preco: 75.00,
        preview: 'img/corte-da-rocha.jpg',
        arquivo: 'corte-da-rocha.jpg',
      },
      {
        id: 'ser-007',
        categoria: 'artistica',
        categoriaArtId: 'serra',
        nome: 'Serra Catarinense',
        preco: 60.00,
        preview: 'img/serra-catarinense.jpg',
        arquivo: 'serra-catarinense.jpg',
      },
      {
        id: 'ser-008',
        categoria: 'artistica',
        categoriaArtId: 'serra',
        nome: 'Estrada Serrana',
        preco: 70.00,
        preview: 'img/estrada-serrana.jpg',
        arquivo: 'estrada-serrana.jpg',
      },
      {
        id: 'ser-009',
        categoria: 'artistica',
        categoriaArtId: 'serra',
        nome: 'Vista do Vale',
        preco: 60.00,
        preview: 'img/vista-do-vale.jpg',
        arquivo: 'vista-do-vale.jpg',
      },
    ],
  },
  {
    id: 'arquitetura',
    nome: 'Arquitetura',
    icone: '',
    fotos: [
      {
        id: 'arq-001',
        categoria: 'artistica',
        categoriaArtId: 'arquitetura',
        nome: 'Casarão Colonial',
        preco: 75.00,
        preview: 'img/casarao-colonial.jpg',
        arquivo: 'casarao-colonial.jpg',
      },
    ],
  },
];

// ── Array global PRODUTOS (mantém compatibilidade com facial.js) ──
const PRODUTOS = [
  ...EVENTOS.flatMap(e => e.fotos),
  ...CATEGORIAS_ARTISTICAS.flatMap(c => c.fotos),
];

// ── DESCONTOS PROGRESSIVOS ────────────────────────────────────
const DESCONTOS = [
  { minFotos: 5, percentual: 20, label: '5+ fotos = 20% off' },
  { minFotos: 3, percentual: 10, label: '3+ fotos = 10% off' },
  { minFotos: 1, percentual: 0,  label: ''                   },
];

function calcularDesconto(qtdFotos) {
  return DESCONTOS.find(d => qtdFotos >= d.minFotos) || DESCONTOS[2];
}